# -*- coding: utf-8 -*-
"""311_fine_tuning_GPT2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/bnsreenu/python_for_microscopists/blob/master/311_fine_tuning_GPT2.ipynb
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

url = "https://socialblade.com/youtube/"

html = requests.get(url)

print (html.text)

print( type (html))

soup = BeautifulSoup(html.text)

body = soup.findAll({"div":{"class":"table-body"}})

body

def prepare_table_row(row):
  lst = [i.text for i in row if i !=u"\n"]
  return dict(rank = int(lst[0]),
              grade=str(lst[1]),
              channel = str(lst([2])) ,
              videos = float(lst[3].replace(",",'')),
              subscribers = float(lst[4].replace(",",'')),
              views= float(lst[5].replace(",",'')))

print (prepare_table_row(body[0]))

data = []
for tr in body:
  datum = prepare_table_row(tr)
  for a tr.find_all('a',href="True"):
    datum['url']= a ['href']
   data.append(datum)

df = pd.DataFrame(data)

df

import seaborn as sns

ax = sns.barplot(x=df['subscribers"'],y=df["channel"])

